#!/bin/bash

# ==============================================================================
# 🛡️ wireguard_admin.sh: Administrera WireGuard VPN Server & Registrera Klienter
# ==============================================================================
# Detta skript körs på VPN-Servern (192.168.200.1 / Server-datorn).
# Det hjälper dig att:
#  1. Initiera servern från grunden (skapa servernycklar & grundkonfiguration)
#  2. Registrera nya klienter (robotar, laptoper) på ett enkelt, interaktivt sätt
#  3. Visa och ta bort registrerade klienter
#  4. Ladda om konfigurationen sömlöst utan att koppla ner befintliga användare
# ==============================================================================

GREEN='\e[32m'
RED='\e[31m'
YELLOW='\e[33m'
BLUE='\e[34m'
BOLD='\e[1m'
NC='\e[0m' # No Color

WG_DIR="/etc/wireguard"
WG_CONF="$WG_DIR/wg0.conf"

# Säkerställ root (sudo)
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}${BOLD}Fel:${NC} Detta skript måste köras med sudo! Kör: ${BOLD}sudo ./wireguard_admin.sh${NC}"
  exit 1
fi

# Kontrollera om WireGuard-verktyg är installerade
if ! command -v wg &>/dev/null; then
  echo -e "${YELLOW}WireGuard är inte installerat på den här servern än.${NC}"
  echo -e "Installerar wireguard-verktyg..."
  apt update && apt install -y wireguard wireguard-tools resolvconf
fi

# Skapa mappen om den saknas
mkdir -p "$WG_DIR"
chmod 700 "$WG_DIR"

# ------------------------------------------------------------------------------
# FUNCTION: Initiera Servern
# ------------------------------------------------------------------------------
init_server() {
  echo -e "\n${BLUE}${BOLD}--- INITIERAR WIREGUARD VPN SERVER ---${NC}"
  
  if [ -f "$WG_CONF" ]; then
    echo -e "${YELLOW}Varning: En konfigurationsfil finns redan på $WG_CONF!${NC}"
    read -p "Vill du skriva över den och skapa en helt ny server? (y/n): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[YyJj] ]]; then
      echo -e "Avbryter initiering."
      return
    fi
  fi

  echo -e "Genererar serverns nyckelpar..."
  wg genkey | tee "$WG_DIR/server_private.key" | wg pubkey > "$WG_DIR/server_public.key"
  chmod 600 "$WG_DIR/server_private.key" "$WG_DIR/server_public.key"

  SRV_PRIV=$(cat "$WG_DIR/server_private.key")
  SRV_PUB=$(cat "$WG_DIR/server_public.key")

  # Hitta aktivt nätverksgränssnitt för internetanslutning (t.ex. enp3s0 eller eth0)
  NET_IFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
  NET_IFACE=${NET_IFACE:-"eth0"}
  echo -e "Detekterade aktivt nätverksgränssnitt: ${BOLD}$NET_IFACE${NC}"

  echo -e "Skapar grundkonfiguration i $WG_CONF..."
  cat <<EOF > "$WG_CONF"
# ==============================================================================
# WireGuard Server Configuration
# Generated by wireguard_admin.sh on $(date)
# ==============================================================================

[Interface]
# Serverns publika nyckel: $SRV_PUB
PrivateKey = $SRV_PRIV
Address = 192.168.200.1/24
ListenPort = 51820

# Aktivera NAT/Routing så klienter kan nå varandra och internet (om tillåtet)
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o $NET_IFACE -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o $NET_IFACE -j MASQUERADE
EOF

  chmod 600 "$WG_CONF"

  # Aktivera IP-forwarding i Linux-kärnan
  echo -e "Aktiverar IP-forwarding i systemet..."
  sysctl -w net.ipv4.ip_forward=1 &>/dev/null
  if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  fi

  # Starta tjänsten
  systemctl daemon-reload
  systemctl enable wg-quick@wg0.service &>/dev/null
  systemctl restart wg-quick@wg0.service &>/dev/null

  # Öppna porten i Ubuntu-brandväggen (ufw) om den är aktiverad
  if command -v ufw &>/dev/null; then
    echo -e "Öppnar port 51820/udp i systemets brandvägg (ufw)..."
    ufw allow 51820/udp &>/dev/null
  fi

  echo -e "${GREEN}✅ Servern är nu initierad och igång!${NC}"
  echo -e "\n${BOLD}Serverdetaljer för dina klienter:${NC}"
  echo -e "  Server Public Key:  ${BLUE}${BOLD}$SRV_PUB${NC}"
  echo -e "  Server IP/Endpoint: ${BLUE}${BOLD}$(hostname -I | awk '{print $1}')${NC} (eller din publika IP-adress)"
  echo -e "  Server Port:        ${BLUE}${BOLD}51820${NC}"
  echo -e "======================================================================"
}

# ------------------------------------------------------------------------------
# FUNCTION: Registrera ny Klient (Peer)
# ------------------------------------------------------------------------------
add_peer() {
  echo -e "\n${BLUE}${BOLD}--- REGISTRERA NY KLIENT (PEER) ---${NC}"
  
  if [ ! -f "$WG_CONF" ]; then
    echo -e "${RED}Fel: Servern är inte initierad än (hittar inte $WG_CONF).${NC}"
    echo -e "Vänligen välj alternativ 1 först för att starta servern."
    return
  fi

  read -p "1. Ange klientens namn/beskrivning (t.ex. Nya Drängen): " PEER_NAME
  if [ -z "$PEER_NAME" ]; then
    echo -e "${RED}Fel: Du måste ange ett namn!${NC}"
    return
  fi

  read -p "2. Ange klientens Public Key: " PEER_KEY
  if [ -z "$PEER_KEY" ]; then
    echo -e "${RED}Fel: Du måste ange en Public Key!${NC}"
    return
  fi

  # Kontrollera om nyckeln redan finns registrerad
  if grep -q "$PEER_KEY" "$WG_CONF"; then
    echo -e "${RED}Fel: Denna Public Key är redan registrerad i $WG_CONF!${NC}"
    return
  fi

  # Föreslå en ledig IP-adress
  echo -e "3. Välj IP-adress för klienten i VPN-nätverket (192.168.200.x):"
  echo -e "   Vanliga förvalda adresser:"
  echo -e "     - Gunnars dator (Laptop):  192.168.200.3"
  echo -e "     - Gamla Drängen (Pi):      192.168.200.4"
  echo -e "     - MacTrac EIP (Jetson):    192.168.200.7"
  echo -e "     - Nya Drängen (Pi):        192.168.200.8"
  
  read -p "   Ange IP (Standard: 192.168.200.8): " PEER_IP
  PEER_IP=${PEER_IP:-"192.168.200.8"}

  # Kontrollera om IP redan är upptagen i filen
  if grep -q "$PEER_IP/32" "$WG_CONF"; then
    echo -e "${YELLOW}Varning: IP-adressen $PEER_IP är redan tilldelad till en annan peer i filen!${NC}"
    read -p "Vill du fortsätta ändå? (y/n): " CONTINUE_IP
    if [[ ! "$CONTINUE_IP" =~ ^[YyJj] ]]; then
      return
    fi
  fi

  # Lägg till peeren i wg0.conf
  echo -e "\nLägger till peeren ${BOLD}$PEER_NAME${NC} ($PEER_IP) i $WG_CONF..."
  cat <<EOF >> "$WG_CONF"

# Peer: $PEER_NAME
[Peer]
PublicKey = $PEER_KEY
AllowedIPs = $PEER_IP/32
EOF

  echo -e "${GREEN}✅ Klienten tillagd i konfigurationsfilen!${NC}"

  # Ladda om WireGuard sömlöst utan att störa befintliga anslutningar!
  echo -e "Laddar om WireGuard-konfigurationen live..."
  if command -v wg-quick &>/dev/null; then
    wg syncconf wg0 <(wg-quick strip wg0) &>/dev/null
    echo -e "${GREEN}✅ WireGuard laddades om sömlöst! Klienten kan ansluta nu.${NC}"
  else
    systemctl restart wg-quick@wg0
    echo -e "${GREEN}✅ WireGuard-tjänsten startades om! Klienten kan ansluta nu.${NC}"
  fi
}

# ------------------------------------------------------------------------------
# FUNCTION: Visa Registrerade Klienter
# ------------------------------------------------------------------------------
list_peers() {
  echo -e "\n${BLUE}${BOLD}--- REGISTRERADE ANVÄNDARE & LIVE-STATUS ---${NC}"
  if [ ! -f "$WG_CONF" ]; then
    echo -e "${RED}Servern är inte initierad än.${NC}"
    return
  fi

  echo -e "${BOLD}Konfigurerade användare i $WG_CONF:${NC}"
  grep -E '^# Peer:|^AllowedIPs' "$WG_CONF" | sed 's/# Peer: /👤 Name: /g' | sed 's/AllowedIPs = /   IP:   /g'
  
  echo -e "\n${BOLD}Live WireGuard Status (Aktiva anslutningar):${NC}"
  wg show
}

# ------------------------------------------------------------------------------
# FUNCTION: Ta bort en Klient (Peer)
# ------------------------------------------------------------------------------
remove_peer() {
  echo -e "\n${BLUE}${BOLD}--- TA BORT EN REGRISTRERAD KLIENT ---${NC}"
  if [ ! -f "$WG_CONF" ]; then
    echo -e "${RED}Servern är inte initierad än.${NC}"
    return
  fi

  echo -e "Följande klienter hittades i $WG_CONF:"
  # Hitta alla linjer med Peer-namn och låt användaren skriva in namnet eller IP
  grep -n '^# Peer:' "$WG_CONF"
  
  echo ""
  read -p "Mata in namnet på peeren du vill ta bort (exakt match, t.ex. Nya Drängen): " DEL_NAME
  if [ -z "$DEL_NAME" ]; then
    echo -e "${RED}Avbrutet.${NC}"
    return
  fi

  # Kolla om peeren finns i filen
  if ! grep -q "# Peer: $DEL_NAME" "$WG_CONF"; then
    echo -e "${RED}Hittade ingen peer med namnet '$DEL_NAME'.${NC}"
    return
  fi

  # Ta bort peer-blocket (kommentaren och efterföljande [Peer] block fram till nästa peer eller slut på fil)
  # Vi använder en temporär fil för att göra detta säkert
  TEMP_FILE=$(mktemp)
  
  # Ett litet awk-script som plockar bort blocket som matchar peernamnet
  awk -v name="$DEL_NAME" '
    BEGIN { skip = 0 }
    $0 ~ "# Peer: " name { skip = 3; next } # Hoppa över kommentarsraden, [Peer], PublicKey och AllowedIPs
    skip > 0 { skip--; next }
    { print }
  ' "$WG_CONF" > "$TEMP_FILE"

  mv "$TEMP_FILE" "$WG_CONF"
  chmod 600 "$WG_CONF"
  
  echo -e "${GREEN}✅ Peer '$DEL_NAME' har tagits bort från $WG_CONF!${NC}"
  
  # Ladda om WireGuard sömlöst
  if command -v wg-quick &>/dev/null; then
    wg syncconf wg0 <(wg-quick strip wg0) &>/dev/null
  else
    systemctl restart wg-quick@wg0
  fi
  echo -e "${GREEN}✅ WireGuard laddades om. Ändringarna är aktiva live!${NC}"
}

# ------------------------------------------------------------------------------
# 🎛️ Huvudmeny Loop
# ------------------------------------------------------------------------------
while true; do
  echo -e "\n${BLUE}${BOLD}======================================================================${NC}"
  echo -e "${BLUE}${BOLD}   🛡️  WIREGUARD VPN SERVER ADMINISTRATÖR-VERKTYG (wg0)  🛡️${NC}"
  echo -e "${BLUE}${BOLD}======================================================================${NC}"
  echo -e "Välj en åtgärd:"
  echo -e "  1) ${BOLD}Initiera VPN-Server${NC} (Skapa ny server från grunden)"
  echo -e "  2) ${BOLD}Registrera ny Klient (Peer)${NC} (Lägg till robot/PC till servern)"
  echo -e "  3) ${BOLD}Visa Registrerade Klienter & Status${NC} (Lista alla)"
  echo -e "  4) ${BOLD}Ta bort en Klient${NC} (Ta bort robot/PC från servern)"
  echo -e "  5) Avsluta"
  echo -e "======================================================================"
  
  read -p "Ange val (1-5): " MAIN_CHOICE
  
  case $MAIN_CHOICE in
    1) init_server ;;
    2) add_peer ;;
    3) list_peers ;;
    4) remove_peer ;;
    5) echo -e "Avslutar administratörsverktyget. Hejdå!"; exit 0 ;;
    *) echo -e "${RED}Ogiltigt val, försök igen.${NC}" ;;
  esac
done
